title: Tooba Khullat
logo: /assets/img/headshot.jpeg
description: 
  Data professional with over 2 years of commercial experience in analytics, product development and a master's degree in Data Science from Imperial College London. 
  Currently at All Inclusive Training (FinTech) as a Data Analyst and previously at HealthLumen (HealthTech) as a contractor. 
  <br><br>
  <a href="https://www.linkedin.com/in/tooba-khullat-4a84771aa/">View My LinkedIn Profile</a>
# show_downloads: true

theme: jekyll-theme-minimal
style: styles.css



