title: Tooba Khullat
description: With a master's degree in Data Science from Imperial College London, I possess a robust foundation in harnessing data-driven insights. However, my enthusiasm extends beyond data analytics; I am deeply excited about the dynamic interplay of business and finance. Currently, as a part-time data analyst at All Inclusive Training, I thrive in applying analytical techniques to drive business growth and financial stability. Prior roles as a data engineer and data scientist at HealthLumen sharpened my ability to convert data into strategic assets. Moreover, my personal projects, which are both innovative and complex, exemplify my dedication to exploring the intersections of data science, business, finance, and health.
  <br><br>
  <a href="https://www.linkedin.com/in/tooba-khullat-4a84771aa/">View My LinkedIn Profile</a>
# show_downloads: true

theme: jekyll-theme-minimal
style: styles.css



