title: Tooba Khullat
logo: /assets/img/IMG_1973.jpeg
description: Data Scientist with 1 year of commercial experience in analytics, product development and a master's degree in Data Science from Imperial College London. Previously at HealthLumen (HealthTech) as a contractor. 
show_downloads: true
theme: jekyll-theme-minimal


