title: Tooba Khullat
description: 
  Data professional with over 2 years of commercial experience in analytics and product development. I have a master's degree in Data Science from Imperial College London. 
  I am currently a data analyst at All Inclusive Training and was previously a data engineer and data scientist at HealthLumen. 
  <br><br>
  <a href="https://www.linkedin.com/in/tooba-khullat-4a84771aa/">View My LinkedIn Profile</a>
# show_downloads: true

theme: jekyll-theme-minimal
style: styles.css



